language: php

php:
      - 7.4
      - 8.0

before_script:
      - travis_retry composer update

script:
      - vendor/bin/phpunit  --coverage-clover coverage.xml

after_success:
      - bash <(curl -s https://codecov.io/bash)
      

